catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - src/*
catalog:
  '@antfu/eslint-config': ^7.2.0
  '@oiij/tsconfig': ^0.0.1
  '@types/node': ^25.2.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vitest/ui': ^4.0.18
  bumpp: ^10.4.0
  commitlint: ^20.4.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  esno: ^4.8.0
  lint-staged: ^16.2.7
  simple-git-hooks: ^2.13.1
  taze: ^19.9.2
  tsdown: ^0.20.2
  typescript: ^5.9.3
  unplugin-vue: ^7.1.1
  vite: ^7.3.1
  vitepress: ^1.6.4
  vitepress-demo-plugin: ^1.5.1
  vitest: ^4.0.18
  vue-tsc: ^3.2.4
