catalogMode: prefer

shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: warn

packages:
  - src/*

catalog:
  '@antfu/eslint-config': ^7.7.2
  '@oiij/tsconfig': ^0.0.1
  '@types/node': ^25.4.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vitest/ui': ^4.0.18
  bumpp: ^10.4.1
  commitlint: ^20.4.3
  cz-git: ^1.12.0
  czg: ^1.12.0
  eslint: ^10.0.3
  eslint-plugin-format: ^2.0.1
  esno: ^4.8.0
  lint-staged: ^16.3.3
  simple-git-hooks: ^2.13.1
  taze: ^19.10.0
  tsdown: ^0.21.2
  typescript: ^5.9.3
  unplugin-vue: ^7.1.1
  vite: ^7.3.1
  vitepress: ^1.6.4
  vitepress-demo-plugin: ^1.5.1
  vitest: ^4.0.18
  vue-tsc: ^3.2.5
